# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mercilessly Refactored Life
email: brycekbargar@gmail.com
description: "A collection of refactorings as I try to clean up the technical debt in my life, my code and my music"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.brycekbargar.com" # the base hostname & protocol for your site
github_username:  brycekbargar

# Jekyll settings
permalink: /:categories/:title.html

# Build settings
markdown: kramdown
